<?php

namespace XTeam\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function findQuestionsByTags($tagName) {

        return $this->createQueryBuilder('q')
            ->join('q.tags', 't', 'WITH', 't.tagname=:tag')
            ->setParameter('tag', $tagName)
            ->getQuery()
            ->getResult();

    }

}
