<?php

namespace XTeam\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionRepository extends EntityRepository
{
}
