<?php

namespace XTeam\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * statRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class statRepository extends EntityRepository
{
}
