<?php

namespace XTeam\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tagRepository extends EntityRepository
{
}
